head:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - head_neck_pitch_joint
      - head_neck_roll_joint
      - head_neck_yaw_joint
      - head_head_tilt_joint
      - head_eyes_tilt_joint
      - head_left_eye_joint
      - head_right_eye_joint

    gains: 
      head_neck_pitch_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      head_neck_roll_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      head_neck_yaw_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      head_head_tilt_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      head_eyes_tilt_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      head_left_eye_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      head_right_eye_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}

  joint_trajectory_effort_controller: 
    type: "effort_controllers/JointTrajectoryController"
    joints: 
      - head_neck_pitch_joint
      - head_neck_roll_joint
      - head_neck_yaw_joint
      - head_head_tilt_joint
      - head_eyes_tilt_joint
      - head_left_eye_joint
      - head_right_eye_joint

    gains: # Required because we're controlling an effort interface
      head_neck_pitch_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      head_neck_roll_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      head_neck_yaw_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      head_head_tilt_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      head_eyes_tilt_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      head_left_eye_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      head_right_eye_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}

  # Position Controllers ---------------------------------------
  head_neck_pitch_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: head_neck_pitch_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  head_neck_roll_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: head_neck_roll_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  head_neck_yaw_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: head_neck_yaw_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  head_head_tilt_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: head_head_tilt_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  head_eyes_tilt_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: head_eyes_tilt_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  head_left_eye_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: head_left_eye_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  head_right_eye_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: head_right_eye_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}